### ISSUE TITLE
keybind issue

### ISSUE THREAD

**Issue by Tavish5** [DevPieter/Znn-Clicker#2]
I am not able to set enable/ disable keybind to my middle mouse button, v1 had it set to middle mouse button by default if keybinding middle mouse button in ZNN clicker isn't possible can you make the Auto double clicker v1 availiable

**Comment by DevPieter** [comment]
I'm adding mouse button support to the keybindings in a future update.
For now, you can download [Auto Double Clicker V1](https://www.mediafire.com/file/vildify980y8t3i/Auto_Double_Clicker.exe/file).

**Comment by Tavish5** [comment]
thanks for quick reply ;)
